server:
    port: 9090
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/springboot-vue?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
    jackson:
        date-format: yyyy-MM-dd

logging:
    level:
        com.example.demo.mapper: debug

files:
    upload:
        path: C:/Users/Administrator/Desktop/springboot+vue/files/


mybatis:
  configuration:
      map-underscore-to-camel-case: true